// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestoManager.Business.Infrastructure.Persistence;

#nullable disable

namespace RestoManager.Business.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BusinessDbContext))]
    [Migration("20260911223144_EmployeeUserLink")]
    partial class EmployeeUserLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestoManager.Business.Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer")
                        .HasColumnName("loyalty_points");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Customers.GiftCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("balance");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("card_number");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.HasKey("Id")
                        .HasName("pk_gift_cards");

                    b.HasIndex("CardNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_gift_cards_card_number");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_gift_cards_customer_id");

                    b.ToTable("gift_cards", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Customers.GiftCardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("GiftCardId")
                        .HasColumnType("integer")
                        .HasColumnName("gift_card_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("transaction_time");

                    b.HasKey("Id")
                        .HasName("pk_gift_card_transactions");

                    b.HasIndex("GiftCardId")
                        .HasDatabaseName("ix_gift_card_transactions_gift_card_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_gift_card_transactions_order_id");

                    b.ToTable("gift_card_transactions", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Customers.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date")
                        .HasColumnName("review_date");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_reviews_branch_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reviews_customer_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_rating", "rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Delivery.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actual_time");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("delivery_address");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("EstimatedTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("estimated_time");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_deliveries_driver_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_deliveries_order_id");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Delivery.DeliveryDriver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_delivery_drivers");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_delivery_drivers_employee_id");

                    b.ToTable("delivery_drivers", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.DiningRoom.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer")
                        .HasColumnName("party_size");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reservation_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_reservations_branch_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reservations_customer_id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_reservations_table_id");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.DiningRoom.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operational_status");

                    b.HasKey("Id")
                        .HasName("pk_tables");

                    b.HasIndex("BranchId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_tables_branch_id_number");

                    b.ToTable("tables", null, t =>
                        {
                            t.HasCheckConstraint("ck_tables_operational_status", "operational_status IN ('ACTIVE', 'CLEANING', 'OUT_OF_SERVICE')");
                        });
                });

            modelBuilder.Entity("RestoManager.Business.Domain.DiningRoom.TableSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closed_at");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("opened_at");

                    b.Property<int>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    b.HasKey("Id")
                        .HasName("pk_table_sessions");

                    b.HasIndex("TableId")
                        .IsUnique()
                        .HasDatabaseName("ux_table_sessions_one_open_per_table")
                        .HasFilter("closed_at IS NULL");

                    b.ToTable("table_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_table_sessions_closed_after_opened", "closed_at IS NULL OR closed_at >= opened_at");

                            t.HasCheckConstraint("ck_table_sessions_guest_count", "guest_count > 0");
                        });
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Inventory.BranchInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("stock_quantity");

                    b.HasKey("Id")
                        .HasName("pk_branch_inventory");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_branch_inventory_ingredient_id");

                    b.HasIndex("BranchId", "IngredientId")
                        .IsUnique()
                        .HasDatabaseName("ix_branch_inventory_branch_id_ingredient_id");

                    b.ToTable("branch_inventory", null, t =>
                        {
                            t.HasCheckConstraint("ck_branch_inventory_stock_non_negative", "stock_quantity >= 0");
                        });
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Inventory.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("ReorderPoint")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("reorder_point");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<DateTime>("MovementTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("movement_time");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_type");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_type");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movements");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_inventory_movements_employee_id");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_inventory_movements_ingredient_id");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_inventory_movements_reference_type_reference_id");

                    b.HasIndex("BranchId", "IngredientId", "MovementTime")
                        .HasDatabaseName("ix_inventory_movements_branch_id_ingredient_id_movement_time");

                    b.ToTable("inventory_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movements_quantity", "quantity <> 0");

                            t.HasCheckConstraint("ck_inventory_movements_type", "movement_type IN ('PURCHASE', 'SALE', 'WASTE', 'ADJUSTMENT')");
                        });
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Inventory.WasteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("LoggedBy")
                        .HasColumnType("integer")
                        .HasColumnName("logged_by");

                    b.Property<DateTime>("LoggedTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("logged_time");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_waste_logs");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_waste_logs_branch_id");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_waste_logs_ingredient_id");

                    b.HasIndex("LoggedBy")
                        .HasDatabaseName("ix_waste_logs_logged_by");

                    b.ToTable("waste_logs", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.KitchenStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_kitchen_stations");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_kitchen_stations_branch_id");

                    b.ToTable("kitchen_stations", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("ImageKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("image_key");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_menu_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_menu_items_category_id");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.MenuItemBranchAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.HasKey("Id")
                        .HasName("pk_menu_item_branch_availability");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_menu_item_branch_availability_menu_item_id");

                    b.HasIndex("BranchId", "MenuItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_menu_item_branch_availability_branch_id_menu_item_id");

                    b.ToTable("menu_item_branch_availability", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.RecipeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<decimal>("QuantityRequired")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity_required");

                    b.HasKey("Id")
                        .HasName("pk_recipe_items");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipe_items_ingredient_id");

                    b.HasIndex("MenuItemId", "IngredientId")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_items_menu_item_id_ingredient_id");

                    b.ToTable("recipe_items", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.StationMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.HasKey("Id")
                        .HasName("pk_station_menu_items");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_station_menu_items_menu_item_id");

                    b.HasIndex("StationId", "MenuItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_station_menu_items_station_id_menu_item_id");

                    b.ToTable("station_menu_items", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closing_time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opening_time");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PublicSlug")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("public_slug");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("PublicSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_public_slug");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_branches_restaurant_id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_departments_branch_id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_employees_branch_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_employees_role_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.EmployeeLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("leave_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_employee_leaves");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_leaves_employee_id");

                    b.ToTable("employee_leaves", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_number");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal>("ScheduledHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("scheduled_hours");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_shifts");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_shifts_employee_id");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Purchasing.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_purchase_orders_branch_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_orders_supplier_id");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Purchasing.PurchaseOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_items");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_purchase_order_items_ingredient_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchase_order_items_purchase_order_id");

                    b.ToTable("purchase_order_items", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Purchasing.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_discounts");

                    b.ToTable("discounts", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    b.Property<int?>("TableSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("table_session_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_orders_branch_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_orders_employee_id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_orders_table_id");

                    b.HasIndex("TableSessionId")
                        .HasDatabaseName("ix_orders_table_session_id");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_channel", "channel IN ('MESA', 'BARRA', 'TAKEAWAY', 'DELIVERY')");

                            t.HasCheckConstraint("ck_orders_channel_table", "(channel = 'MESA' AND table_id IS NOT NULL) OR (channel <> 'MESA' AND table_id IS NULL AND table_session_id IS NULL)");
                        });
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.OrderDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AppliedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("applied_amount");

                    b.Property<int>("DiscountId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("pk_order_discounts");

                    b.HasIndex("DiscountId")
                        .HasDatabaseName("ix_order_discounts_discount_id");

                    b.HasIndex("OrderId", "DiscountId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_discounts_order_id_discount_id");

                    b.ToTable("order_discounts", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_order_items_menu_item_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payments_order_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Tax.MenuItemTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("TaxRateId")
                        .HasColumnType("integer")
                        .HasColumnName("tax_rate_id");

                    b.HasKey("Id")
                        .HasName("pk_menu_item_taxes");

                    b.HasIndex("TaxRateId")
                        .HasDatabaseName("ix_menu_item_taxes_tax_rate_id");

                    b.HasIndex("MenuItemId", "TaxRateId")
                        .IsUnique()
                        .HasDatabaseName("ix_menu_item_taxes_menu_item_id_tax_rate_id");

                    b.ToTable("menu_item_taxes", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Tax.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rate");

                    b.HasKey("Id")
                        .HasName("pk_tax_rates");

                    b.ToTable("tax_rates", (string)null);
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Customers.GiftCard", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_gift_cards_customers_customer_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Customers.GiftCardTransaction", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Customers.GiftCard", null)
                        .WithMany()
                        .HasForeignKey("GiftCardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_gift_card_transactions_gift_cards_gift_card_id");

                    b.HasOne("RestoManager.Business.Domain.Sales.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_gift_card_transactions_orders_order_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Customers.Review", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_customers_customer_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Delivery.Delivery", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Delivery.DeliveryDriver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_delivery_drivers_driver_id");

                    b.HasOne("RestoManager.Business.Domain.Sales.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_orders_order_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Delivery.DeliveryDriver", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_drivers_employees_employee_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.DiningRoom.Reservation", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_customers_customer_id");

                    b.HasOne("RestoManager.Business.Domain.DiningRoom.Table", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_tables_table_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.DiningRoom.Table", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tables_branches_branch_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.DiningRoom.TableSession", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.DiningRoom.Table", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_table_sessions_tables_table_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Inventory.BranchInventory", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_branch_inventory_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Inventory.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_branch_inventory_ingredients_ingredient_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Organization.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_inventory_movements_employees_employee_id");

                    b.HasOne("RestoManager.Business.Domain.Inventory.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_ingredients_ingredient_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Inventory.WasteLog", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_waste_logs_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Inventory.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_waste_logs_ingredients_ingredient_id");

                    b.HasOne("RestoManager.Business.Domain.Organization.Employee", null)
                        .WithMany()
                        .HasForeignKey("LoggedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_waste_logs_employees_logged_by");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.KitchenStation", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_kitchen_stations_branches_branch_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.MenuItem", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Menu.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_categories_category_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.MenuItemBranchAvailability", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_branch_availability_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Menu.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_branch_availability_menu_items_menu_item_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.RecipeItem", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Inventory.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_items_ingredients_ingredient_id");

                    b.HasOne("RestoManager.Business.Domain.Menu.MenuItem", null)
                        .WithMany("Recipe")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_items_menu_items_menu_item_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.StationMenuItem", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Menu.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_station_menu_items_menu_items_menu_item_id");

                    b.HasOne("RestoManager.Business.Domain.Menu.KitchenStation", null)
                        .WithMany("MenuItems")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_menu_items_kitchen_stations_station_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Branch", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_branches_restaurants_restaurant_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Department", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_departments_branches_branch_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Employee", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_employees_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Organization.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.HasOne("RestoManager.Business.Domain.Organization.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_employees_roles_role_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.EmployeeLeave", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_employee_leaves_employees_employee_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Organization.Shift", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_employees_employee_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Purchasing.PurchaseOrder", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Purchasing.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_suppliers_supplier_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Purchasing.PurchaseOrderItem", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Inventory.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_ingredients_ingredient_id");

                    b.HasOne("RestoManager.Business.Domain.Purchasing.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_purchase_orders_purchase_order_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.Order", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Organization.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_orders_branches_branch_id");

                    b.HasOne("RestoManager.Business.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_orders_customers_customer_id");

                    b.HasOne("RestoManager.Business.Domain.Organization.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_orders_employees_employee_id");

                    b.HasOne("RestoManager.Business.Domain.DiningRoom.Table", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_orders_tables_table_id");

                    b.HasOne("RestoManager.Business.Domain.DiningRoom.TableSession", null)
                        .WithMany()
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_orders_table_sessions_table_session_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.OrderDiscount", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Sales.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_discounts_discounts_discount_id");

                    b.HasOne("RestoManager.Business.Domain.Sales.Order", null)
                        .WithMany("Discounts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_discounts_orders_order_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.OrderItem", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Menu.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_menu_items_menu_item_id");

                    b.HasOne("RestoManager.Business.Domain.Sales.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.Payment", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Sales.Order", null)
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_orders_order_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Tax.MenuItemTax", b =>
                {
                    b.HasOne("RestoManager.Business.Domain.Menu.MenuItem", null)
                        .WithMany("Taxes")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_taxes_menu_items_menu_item_id");

                    b.HasOne("RestoManager.Business.Domain.Tax.TaxRate", null)
                        .WithMany()
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_taxes_tax_rates_tax_rate_id");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.KitchenStation", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Menu.MenuItem", b =>
                {
                    b.Navigation("Recipe");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Purchasing.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestoManager.Business.Domain.Sales.Order", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
