-- Restaurant management schema (resto_business) - v4, regenerado desde el esquema real
-- Este archivo es un documento de referencia/diseño; el esquema real y su historia
-- viven en las migraciones de EF Core (backend/business/.../Infrastructure/Persistence/Migrations).
-- v1-v3 se mantenían a mano y quedaron desactualizados a medida que las migraciones avanzaban
-- (Fases 4-11: baja lógica, disponibilidad por sucursal, punto de reposición, carta pública, etc.)
-- sin que nadie las volcara acá. v4 se generó a partir del esquema vivo de una base ya migrada
-- (información de information_schema/pg_catalog), no a mano, para que vuelva a ser fiel.
-- Para regenerarlo: `dotnet ef migrations script` (o inspeccionar la base migrada) y adaptar
-- al estilo de este archivo.
--
-- Changes implemented (v1):
-- 1. orders.customer_id is nullable for anonymous consumers.
-- 2. inventory_movements provides stock ingress/egress traceability.
-- 3. ingredients is a catalog; stock is held per branch in branch_inventory.
-- 4. tables.operational_status only represents physical/operational availability.
-- 5. table_sessions represents actual table occupancy; application derives AVAILABLE/RESERVED/OCCUPIED.
-- 6. orders.table_session_id optionally links an order to its table occupancy session.
-- Changes implemented (v2 — audit fixes):
-- 7. deliveries.actual_time is nullable (unknown until the delivery actually completes).
-- 8. orders.table_id is nullable (delivery, takeaway, and bar orders have no dine-in table).
-- 9. Added UNIQUE constraints: tables(branch_id, number), gift_cards.card_number,
--    recipe_items(menu_item_id, ingredient_id), station_menu_items(station_id, menu_item_id),
--    menu_item_taxes(menu_item_id, tax_rate_id), order_discounts(order_id, discount_id).
-- 10. reviews.rating is constrained to 1-5; order_items.notes and reviews.comment are now optional.
-- 11. All PKs use GENERATED BY DEFAULT AS IDENTITY (was plain integer).
-- Changes implemented (v3 — bar consumption, corrected design):
-- 12. Bar consumption is NOT modeled as a table. It does not fit the exclusive-occupancy
--     semantics of tables/table_sessions: unrelated customers can consume at the bar
--     concurrently, and the system deliberately does not manage bar capacity/space.
--     orders.channel (MESA | BARRA | TAKEAWAY | DELIVERY) is the explicit, stored
--     classification. A CHECK constraint enforces that MESA requires table_id, and every
--     other channel has neither table_id nor table_session_id. Because the bar is not a row
--     in "tables", it is structurally unreservable — reservations.table_id can only ever
--     reference a dine-in table.
-- Changes implemented (v4 — catch-up with Fases 4-12b, sin cambios de diseño nuevos acá):
-- 13. menu_items / ingredients: baja lógica (deleted_at nullable; el repositorio filtra las
--     filas borradas, no hay borrado físico ni cascada de recetas/inventario). Issue #47.
-- 14. menu_items.image_key (nullable): referencia a la imagen del plato en el storage de
--     archivos (servida bajo /media/menu), no la imagen en sí.
-- 15. ingredients.reorder_point: umbral de reposición usado por el reporte de bajo stock.
-- 16. menu_item_branch_availability (nueva tabla): disponibilidad del plato por sucursal,
--     UNIQUE (branch_id, menu_item_id) — reemplaza el booleano global que tenía menu_items.
-- 17. branches.public_slug (nullable, UNIQUE): slug de la carta pública por QR (Fase 11).
-- 18. employees.user_id (nullable, no es FK real: vive en otra base, resto_identity, servida
--     por la Auth API): rastro de qué empleado ya tiene un login vinculado; lo setea el panel
--     de administración al dar de alta el acceso, nunca a mano.
-- Dialect note: the partial unique index at the end uses PostgreSQL syntax.

CREATE TABLE "branch_inventory" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "ingredient_id" integer NOT NULL,
  "stock_quantity" decimal(10,2) NOT NULL,
  UNIQUE ("branch_id", "ingredient_id"),
  CHECK ("stock_quantity" >= 0)
);

CREATE TABLE "branches" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurant_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "address" varchar(255) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "email" varchar(100) NOT NULL,
  "opening_time" time NOT NULL,
  "closing_time" time NOT NULL,
  "public_slug" varchar(60),
  UNIQUE ("public_slug")
);

CREATE TABLE "categories" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" varchar(255) NOT NULL
);

CREATE TABLE "customers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "email" varchar(100) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "loyalty_points" integer NOT NULL
);

CREATE TABLE "deliveries" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "driver_id" integer NOT NULL,
  "delivery_address" varchar(255) NOT NULL,
  "estimated_time" timestamp NOT NULL,
  "actual_time" timestamp,
  "status" varchar(50) NOT NULL
);

CREATE TABLE "delivery_drivers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" integer NOT NULL,
  "vehicle_type" varchar(50) NOT NULL,
  "license_plate" varchar(20) NOT NULL
);

CREATE TABLE "departments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" varchar(255) NOT NULL
);

CREATE TABLE "discounts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "type" varchar(50) NOT NULL,
  "value" decimal(10,2) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL
);

CREATE TABLE "employee_leaves" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" integer NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "leave_type" varchar(50) NOT NULL,
  "status" varchar(50) NOT NULL
);

CREATE TABLE "employees" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "department_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "email" varchar(100) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "hire_date" date NOT NULL,
  "user_id" integer
);

CREATE TABLE "gift_card_transactions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gift_card_id" integer NOT NULL,
  "order_id" integer NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "transaction_time" timestamp NOT NULL
);

CREATE TABLE "gift_cards" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" integer NOT NULL,
  "card_number" varchar(50) NOT NULL,
  "balance" decimal(10,2) NOT NULL,
  "expiry_date" date NOT NULL,
  UNIQUE ("card_number")
);

CREATE TABLE "ingredients" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "unit" varchar(20) NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "reorder_point" decimal(10,2) NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "inventory_movements" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "ingredient_id" integer NOT NULL,
  "movement_type" varchar(50) NOT NULL,
  "quantity" decimal(10,2) NOT NULL,
  "movement_time" timestamp NOT NULL,
  "reference_type" varchar(50),
  "reference_id" integer,
  "employee_id" integer,
  CHECK ("movement_type" IN ('PURCHASE', 'SALE', 'WASTE', 'ADJUSTMENT')),
  CHECK ("quantity" <> 0)
);

CREATE TABLE "kitchen_stations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" varchar(255) NOT NULL
);

CREATE TABLE "menu_item_branch_availability" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "menu_item_id" integer NOT NULL,
  "is_available" boolean NOT NULL,
  UNIQUE ("branch_id", "menu_item_id")
);

CREATE TABLE "menu_item_taxes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "menu_item_id" integer NOT NULL,
  "tax_rate_id" integer NOT NULL,
  UNIQUE ("menu_item_id", "tax_rate_id")
);

CREATE TABLE "menu_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" varchar(255) NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "is_available" boolean NOT NULL,
  "image_key" varchar(200),
  "deleted_at" timestamp
);

CREATE TABLE "order_discounts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "discount_id" integer NOT NULL,
  "applied_amount" decimal(10,2) NOT NULL,
  UNIQUE ("order_id", "discount_id")
);

CREATE TABLE "order_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "menu_item_id" integer NOT NULL,
  "quantity" integer NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "notes" varchar(255)
);

CREATE TABLE "orders" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "table_id" integer,
  "employee_id" integer NOT NULL,
  "customer_id" integer,
  "table_session_id" integer,
  "channel" varchar(20) NOT NULL,
  "order_time" timestamp NOT NULL,
  "total_amount" decimal(10,2) NOT NULL,
  "status" varchar(50) NOT NULL,
  CHECK ("channel" IN ('MESA', 'BARRA', 'TAKEAWAY', 'DELIVERY')),
  CHECK ((
    ("channel" = 'MESA' AND "table_id" IS NOT NULL)
    OR ("channel" <> 'MESA' AND "table_id" IS NULL AND "table_session_id" IS NULL)
  ))
);

CREATE TABLE "payments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "payment_method" varchar(50) NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "payment_time" timestamp NOT NULL,
  "status" varchar(50) NOT NULL
);

CREATE TABLE "purchase_order_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_order_id" integer NOT NULL,
  "ingredient_id" integer NOT NULL,
  "quantity" decimal(10,2) NOT NULL,
  "unit_price" decimal(10,2) NOT NULL
);

CREATE TABLE "purchase_orders" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" integer NOT NULL,
  "branch_id" integer NOT NULL,
  "order_date" date NOT NULL,
  "total_amount" decimal(10,2) NOT NULL,
  "status" varchar(50) NOT NULL
);

CREATE TABLE "recipe_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "menu_item_id" integer NOT NULL,
  "ingredient_id" integer NOT NULL,
  "quantity_required" decimal(10,2) NOT NULL,
  "is_public" boolean NOT NULL,
  UNIQUE ("menu_item_id", "ingredient_id")
);

CREATE TABLE "reservations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" integer NOT NULL,
  "branch_id" integer NOT NULL,
  "table_id" integer NOT NULL,
  "reservation_time" timestamp NOT NULL,
  "party_size" integer NOT NULL,
  "status" varchar(50) NOT NULL
);

CREATE TABLE "restaurants" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "address" varchar(255) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "email" varchar(100) NOT NULL,
  "tax_number" varchar(50) NOT NULL
);

CREATE TABLE "reviews" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" integer NOT NULL,
  "branch_id" integer NOT NULL,
  "rating" integer NOT NULL,
  "comment" varchar(500),
  "review_date" date NOT NULL,
  CHECK ("rating" BETWEEN 1 AND 5)
);

CREATE TABLE "roles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" varchar(255) NOT NULL,
  "hourly_rate" decimal(10,2) NOT NULL
);

CREATE TABLE "shifts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" integer NOT NULL,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "scheduled_hours" decimal(5,2) NOT NULL
);

CREATE TABLE "station_menu_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "station_id" integer NOT NULL,
  "menu_item_id" integer NOT NULL,
  UNIQUE ("station_id", "menu_item_id")
);

CREATE TABLE "suppliers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "contact_name" varchar(100) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "email" varchar(100) NOT NULL,
  "address" varchar(255) NOT NULL
);

CREATE TABLE "table_sessions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_id" integer NOT NULL,
  "guest_count" integer NOT NULL,
  "opened_at" timestamp NOT NULL,
  "closed_at" timestamp,
  CHECK ("guest_count" > 0),
  CHECK ("closed_at" IS NULL OR "closed_at" >= "opened_at")
);

CREATE TABLE "tables" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "number" integer NOT NULL,
  "capacity" integer NOT NULL,
  "operational_status" varchar(20) NOT NULL,
  UNIQUE ("branch_id", "number"),
  CHECK ("operational_status" IN ('ACTIVE', 'CLEANING', 'OUT_OF_SERVICE'))
);

CREATE TABLE "tax_rates" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "rate" decimal(5,2) NOT NULL
);

CREATE TABLE "waste_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "ingredient_id" integer NOT NULL,
  "quantity" decimal(10,2) NOT NULL,
  "reason" varchar(255) NOT NULL,
  "logged_time" timestamp NOT NULL,
  "logged_by" integer NOT NULL
);

CREATE UNIQUE INDEX "ux_table_sessions_one_open_per_table"
  ON "table_sessions" ("table_id")
  WHERE (closed_at IS NULL);

ALTER TABLE "branch_inventory" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "branch_inventory" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id");
ALTER TABLE "branches" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("id");
ALTER TABLE "deliveries" ADD FOREIGN KEY ("driver_id") REFERENCES "delivery_drivers" ("id");
ALTER TABLE "deliveries" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "delivery_drivers" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "departments" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "employee_leaves" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "employees" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "employees" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
ALTER TABLE "employees" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "gift_card_transactions" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "gift_card_transactions" ADD FOREIGN KEY ("gift_card_id") REFERENCES "gift_cards" ("id");
ALTER TABLE "gift_cards" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");
ALTER TABLE "inventory_movements" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "inventory_movements" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id");
ALTER TABLE "inventory_movements" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "kitchen_stations" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "menu_item_branch_availability" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "menu_item_branch_availability" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id");
ALTER TABLE "menu_item_taxes" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id");
ALTER TABLE "menu_item_taxes" ADD FOREIGN KEY ("tax_rate_id") REFERENCES "tax_rates" ("id");
ALTER TABLE "menu_items" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");
ALTER TABLE "order_discounts" ADD FOREIGN KEY ("discount_id") REFERENCES "discounts" ("id");
ALTER TABLE "order_discounts" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "order_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("table_session_id") REFERENCES "table_sessions" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");
ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "purchase_order_items" ADD FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders" ("id");
ALTER TABLE "purchase_order_items" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id");
ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id");
ALTER TABLE "recipe_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id");
ALTER TABLE "recipe_items" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id");
ALTER TABLE "reservations" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "reservations" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id");
ALTER TABLE "reservations" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");
ALTER TABLE "reviews" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");
ALTER TABLE "reviews" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "shifts" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "station_menu_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id");
ALTER TABLE "station_menu_items" ADD FOREIGN KEY ("station_id") REFERENCES "kitchen_stations" ("id");
ALTER TABLE "table_sessions" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id");
ALTER TABLE "tables" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "waste_logs" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "waste_logs" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id");
ALTER TABLE "waste_logs" ADD FOREIGN KEY ("logged_by") REFERENCES "employees" ("id");
